// PAGE
export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_ERROR = 'PAGE_ERROR';

// PODCASTS
export const GET_ALL_PODCASTS = 'GET_ALL_PODCASTS';
export const FILTER_PODCASTS = 'FILTER_PODCASTS';
